version: '3.8'

services:

    client:
        build:
            context: /root/DevOps-Assignment/sys-stats
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        volumes: 
            - /root/DevOps-Assignment/sys-stats:/app
            - /app/node_modules
        networks:
            - frontend


    api:
        build: 
            context: /root/DevOps-Assignment/api
            dockerfile: Dockerfile
        command: gunicorn --bind 0.0.0.0:5000 app:app
        ports:
            - "5000:5000"
        volumes:
            - appdata:/var/www/
        networks:
            - frontend
            - backend
    nginx:
        build:
            context: /root/nginx_docker
            dockerfile: Dockerfile
        ports:
            - "80:80"
        networks:
            - frontend
            - nginx


networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge
    nginx:
        driver: bridge
volumes:
    appdata:
        driver: local
